name: aerostack_sdk
version: 0.6.60.6.60.6.40.6.40.6.30.6.30.6.10.6.00.6.00.6.01.0.0
description: Aerostack SDK for Flutter/Dart
homepage: https://aerostack.ai
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  dio: ^5.2.0
  json_annotation: ^6.1.0
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.1