name: aerostack_sdk
version: 0.6.7
description: Aerostack SDK for Flutter/Dart
homepage: https://aerostack.ai
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  dio: ^5.2.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.1